### PR TITLE
[507] UI-only: Link standard tags in /explorer directly to the right entries for the CRE

### PR DESCRIPTION
**Pull request by dlicheva**
[Ticket](https://github.com/OWASP/OpenCRE/issues/507)
This PR makes it so that the standards on the /explorer page now link to the filtered CRE page filtered by them.
For example:
1. A CRE has links to all of these standards: 
Screenshot from 2024-06-08 18-19-23
2. You click on NIST 
Screenshot from 2024-06-08 18-20-41
3. You get the CRE page showing the NIST sections that are related to that CRE: 
Screenshot from 2024-05-26 21-57-47

4. If the link is to an ungrouped standard and has an external link, you would be linked directly to that page:
Screenshot from 2024-06-08 18-20-00
Screenshot from 2024-06-08 18-20-22

### CODE REVIEW

**Comment by robvanderveer** [comment]
This is wonderful!
The idea was that if there is only one resource to jump straight to the hyperlink (if any) of that resource. So if there's only one ASVS entry then clicking the 'tag' will take the user to the ASVS page outside of OpenCRE. If that's not in place yet, no worry; it can always be a second step.

**Comment by dlicheva** [comment]
Hi @robvanderveer, I can do that, but wouldn't it feel inconsistent to the user? e.g. some tags would lead to a CRE page and others would lead to an external page. Once users are out of the website it can be confusing to navigate back. 

Alternatively, if there is only one link, the tag can link to the content on OpenCRE.org? e.g. linking directly to https://opencre.org/node/standard/NIST%20800-53%20v5/section/CM-2%20BASELINE%20CONFIGURATION ? Then the user can navigate to the external resource, through a more obvious link.

What do you think?

**Comment by dlicheva** [comment]
Thanks @robvanderveer, I see ! I think opening the deeper linked standard in a new tab as you suggest, would be the best approach :+1: 
This should be less confusing because openCRE.org/explorer is there for the user to return to, and they get a new tab with the content of the standard.

**Comment by dlicheva** [comment]
Hi @robvanderveer , this is updated now, so if there is a link with a hyperlink and no siblings, you would get a new tab on click. Is this ok?:
[Screencast from 08-06-24 18:22:50.webm](https://github.com/OWASP/OpenCRE/assets/8710269/b7bf397b-51d7-4f55-b657-7d15b61a61d9)

**Comment by robvanderveer** [comment]
Yup that looks amazing.

**Review by northdpole — APPROVED** [review]

**Pull request merged**
