### PR TITLE
Feature/502 Update the header and main navigation

### PR DESCRIPTION
**Pull request by dlicheva**
[Ticket](https://github.com/OWASP/OpenCRE/issues/502)
This PR updates the style and content of the main navigation.

**Changes**:
- add a new main nav link: "Browse"
- style the header and show it on the home page too. Remove the search from the header only on the home page, to avoid duplication.
- add "OR" to the homepage to separate Browse from Search
- adjust page titles (Root CREs and Map Analysis)
- tweak the margins and padding on the pages, so they align with the logo nicely
- Style the header for mobile

**Screenshots**
#### Map Analysis page
Screenshot from 2024-05-03 18-50-47

#### Browse page
Screenshot from 2024-05-03 18-50-37

#### Home page
Screenshot from 2024-05-03 18-50-28

### CODE REVIEW

**Comment by dlicheva** [comment]
We have a new logo, so I'll update it here later when I get it.

**Comment by robvanderveer** [comment]
I love it. nice and simple.
Suggestions:
1. new logo (I sent Spyros the pptx. Feel free to play around with color and orientation of things. Have a look at the LinkedIn OpenCRE page at that logo.
2.Remove search and browse from the home screen and show the search bar in the top
3. somehow most of the screens are kinda white. Wouldn’t it be nice to have a dark blue menu bar, and a white on blue logo? That will make it look better I think, to have that contrast on the page instead of a white slab. If we’d do that, We also need to change the home page. I’m fine with putting the home page content straigt on the page without the blue surrounding border. text-wise you could replace the current ‘OpenCRE’ title with ‘OpenCRE - Open Common Requirement Enumeration’

**Comment by dlicheva** [comment]
Thanks @robvanderveer , that sounds good!

**Comment by dlicheva** [comment]
I'll just wait for the new logo and update this PR when we get it.

**Comment by dlicheva** [comment]
I've updated the header style and added your logo, @robvanderveer . There will be further tweaks from the designer:
Screenshot from 2024-05-21 14-17-33
Screenshot from 2024-05-21 14-17-20

Let me know if you'd like me to edit it further please.

**Review by northdpole — APPROVED** [review]

**Pull request merged**
